#!/usr/bin/env bash
# This script displays a list of running processes filtered to only show lines containing "bash"
# shellcheck disable=SC2009
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | grep bash
