#!/usr/bin/env bash
# This script displays a list of running processes and filters to show only lines containing the word bash.
# shellcheck disable=SC2009

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | grep bash
