#!/usr/bin/env bash
# 7-highlander - Infinite loop that prints "To infinity and beyond" and ignores SIGTERM by printing a message

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
